version: '3.3'
services:
  docker-mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'hvarela'
      MYSQL_PASSWORD: 'beer'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql 
  apiBeer:
    image: com.falabella.api/beers:1.0.0-SNAPSHOT
    depends_on:
      - docker-mysql
    ports:
      - 8080:8080
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_USER: hvarela
      DATABASE_PASSWORD: beer
      DATABASE_NAME: db  
      DATABASE_PORT: 3306
      SPRING_PROFILE: dev
   
# Names our volume
volumes:
  my-db:

